# Generated by Django 5.1.4 on 2024-12-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='health',
            field=models.BigIntegerField(default=100),
        ),
    ]
