# Generated by Django 5.1.4 on 2024-12-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameRest', '0003_race_card_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='agility_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='race',
            name='health_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='race',
            name='intelligence_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='race',
            name='luck_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='race',
            name='strength_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='card',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='gameRest.race'),
            preserve_default=False,
        ),
    ]
